### ISSUE TITLE
The maps dont load

### ISSUE THREAD

**Issue by afshaan4** [ClobberXD/minetest_ctf-maps#1]
I got the capture the flag pvp engine and the subgame
then cloned this repo into the maps directory for capture the flag

But only rubenwardy's maps load, your maps don't, instead I'm stuck in emptiness or in the previous map.

Am i missing dependencies?

here's some screenshots showing the problem:
![screenshot from 2018-03-01 12-50-27](https://user-images.githubusercontent.com/20749736/36832381-4ea039a2-1d51-11e8-8300-de069183b3f8.png)
![screenshot from 2018-03-01 12-44-14](https://user-images.githubusercontent.com/20749736/36832400-5d0f12e2-1d51-11e8-83fa-1682cd93f748.png)

I also suggest adding setup instructions to the readme

**Comment by ClobberXD** [comment]
Hmm.... strange! I have no idea as to how this even works - I will definitely look into it as soon as I find some time to spare. Thanks for bringing it to my attention.

**Comment by ClobberXD** [comment]
I myself do not know how to load new maps in CTF. But I'll definitely look into it when I have more time to spare. Thank you for bringing this to my attention.

EDIT: Support for reading maps from a maps sub-dir is implemented by ctf_maps. Make sure your maps are placed in the /mods/ctf_maps/maps. I'm yet to look into it - in a couple of days maybe...

**Comment by afshaan4** [comment]
>Make sure your maps are placed in the /mods/ctf_maps/maps.

Yup that's want I did, maybe I need to declare it somewhere else? Like in a map init file

 Ill try to get it to work too.

**Comment by ClobberXD** [comment]
Try looking into the ctf_match mod - that's the one (I think) which handles loading the maps for the matches .

**Comment by afshaan4** [comment]
Maybe the issue is the conf file for the map as in rubenwardys maps the conf files 
initiate your position:
```
name = The Bridge
author = rubenwardy
rotation = x
r = 115
h = 140
team.1 = red
team.1.color = red
team.1.pos = -57,-20,93
team.2 = blue
team.2.color = blue
team.2.pos = -74,-16,-70

```
and yours dont:

```
name = Terror in the Tropics
author = ANAND
rotation = x
r = 115
h = 140

```

maybe it spawns you *off* the map in the middle of nowhere
as if you go beyond the glass border you'll see the map is just a block of map floating in the middle of nowhere

**Comment by afshaan4** [comment]
Yay i got it to work, I added the player location and other stuff to your maps .conf files:

```
name = The Swiss Vacation
author = ANAND
rotation = x
r = 115
h = 140
team.1 = red
team.1.color = red
team.1.pos = -57,-20,93
team.2 = blue
team.2.color = blue
team.2.pos = -74,-16,-70

```

and all your maps worked:
![screenshot from 2018-03-03 16-08-54](https://user-images.githubusercontent.com/20749736/36933364-8e1bf514-1efd-11e8-8208-0f3590840a22.png)

**Comment by ClobberXD** [comment]
@afshaan4 : Nicely done! @rubenwardy must add that to his map-creation tutorial right away IMO. I'll post this on the forum if it's okay with you.

**Comment by afshaan4** [comment]
>I'll post this on the forum if it's okay with you.

Go ahead.

**Comment by ClobberXD** [comment]
I've **PMed** @rubenwardy with reference to this issue, and he should get back sooner or later, but meanwhile, the rotation, r, and h parameters already exists in the original .conf file. Also, the 2 bases are already present in the map, so try rectifying the team.1.pos and team.2.pos accordingly, and let me know of its consequences. I'm sorry as I can't verify this myself as loading .schem files into a world takes eons on my PC. Thanks!

### original swiss.conf
`name = The Swiss Vacation`
`author = ANAND`
`rotation = x`
`r = 115`
`h = 140`

**Comment by rubenwardy** [comment]
Simply put the .conf and .schem files into mods/ctf_map/maps or a subfolder in there. For example, you could clone this repo such that mods/ctf_maps/maps/minetest_ctf-maps/swiss.conf exists.

Obviously you need to have the teams defined in any maps you make. Make sure you've got them the right way around - I forget which one, but one team should be +z and the other should be -z. There's no need for that to be in the tutorial as you should've placed the teams in the map creator anyway - I should however block the export button if you haven't done that

**Comment by ClobberXD** [comment]
@rubenwardy - In spite of the flags being placed, the .conf file does not have any of the following parameters:
`team.1 = red`
`team.1.color = red`
`team.1.pos = x,y,z`
`team.2 = blue`
`team.2.color = blue`
`team.2.pos = x,y,z`

If I'm correct, placing the flags or clicking 'Export' should trigger ctf_map to add these to the .conf file, right?

**Comment by rubenwardy** [comment]
Flags aren't remembered between closing and opening MT, so you need to immediately place them then click export

**Comment by ClobberXD** [comment]
I do that _everytime_, but none of the above are added to any of my 3 maps...
